language: php

sudo: false

services: [rabbitmq]

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
    global:
        - LIBRABBITMQ_VERSION=v0.8.0
        - PHPAMQP_VERSION=v1.9.3

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" PHPUNIT_FLAGS="--exclude-group legacy" # See https://github.com/symfony/symfony/issues/22515
    - php: 7.2
      env: LIBRABBITMQ_VERSION="master"
    - php: 7.2
      env: DEPENDENCIES=dev SYMFONY_VERSION="2.8.x-dev" COMPOSER_FLAGS="--prefer-stable"
    - php: 7.2
      env: DEPENDENCIES=dev SYMFONY_VERSION="3.0.x-dev" COMPOSER_FLAGS="--prefer-stable"
  allow_failures:
    - php: nightly

before_install:
  - sudo ./Tests/bin/install_rabbitmq-c.sh
  - ./Tests/bin/install_php-amqp.sh
  - composer self-update
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle:"$SYMFONY_VERSION" symfony/console:"$SYMFONY_VERSION"; fi

install:
  - composer update $COMPOSER_FLAGS

before_script:
  - sh -c "sudo ./Tests/bin/prepare_rabbit.sh"

script: vendor/bin/phpunit $PHPUNIT_FLAGS
