language: php

php: [5.4, 5.5, 5.6, 7.0, hhvm]

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.5
      env: LIBRABBITMQ_VERSION="master"
    - php: 5.6
      env: DEPENDENCIES=dev SYMFONY_VERSION="2.8.x-dev" COMPOSER_FLAGS="--prefer-stable"
    - php: 5.6
      env: DEPENDENCIES=dev SYMFONY_VERSION="3.0.x-dev" COMPOSER_FLAGS="--prefer-stable"
  allow_failures:
    - php: hhvm

services: [rabbitmq]

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [[ ! $skip && ! $PHP = hhvm* ]]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle:"$SYMFONY_VERSION" symfony/console:"$SYMFONY_VERSION"; fi

install:
  - composer update $COMPOSER_FLAGS

before_script:
  - sh -c 'if [ "$LIBRABBITMQ_VERSION" != "" ]; then ./Tests/bin/install_librabbitmq.sh; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi;'
  - sh -c "sudo ./Tests/bin/prepare_rabbit.sh"

# Due to not yet solved issue with phpdocumentor & php 5.5 https://github.com/phpDocumentor/ReflectionDocBlock/issues/80
script: bin/phpunit
