language: php

php: [5.4, 5.5, 5.6, 7.0]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: DEPENDENCIES=dev SYMFONY_VERSION="2.8.x-dev" COMPOSER_FLAGS="--prefer-stable"
    - php: 5.6
      env: DEPENDENCIES=dev SYMFONY_VERSION="3.0.x-dev" COMPOSER_FLAGS="--prefer-stable"

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle:"$SYMFONY_VERSION"; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/console:"$SYMFONY_VERSION"; fi

install:
  - composer update $COMPOSER_FLAGS
